rear_unit_base_link2pandar_40p_rear_base_link:
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 1.57079
rear_unit_base_link2pandar_qt_rear_base_link:
  x: 0.018
  y: 0.0
  z: 0.130
  roll: 0.0
  pitch: 0.0
  yaw: 1.57079
rear_unit_base_link2camera3:
  x: -0.004
  y: -0.087
  z: 0.110
  roll: 3.141592
  pitch: 0.0
  yaw: 0.0
