sensor_kit_base_link2velodyne_front_base_link:
  x: 0.030
  y: -0.003
  z: 0.075
  roll: 0.0
  pitch: 0.0
  yaw: -0.025
sensor_kit_base_link2livox_front_left_base_link:
  x: 0.397
  y: 0.287
  z: -0.3849
  roll: 0.0
  pitch: 0.0
  yaw: 0.673
sensor_kit_base_link2livox_front_center_base_link:
  x:  0.397
  y: -0.06
  z: -0.3849
  roll: 0.00
  pitch: 0.00
  yaw: -0.03
sensor_kit_base_link2livox_front_right_base_link:
  x: 0.397
  y: -0.342
  z: -0.3849
  roll: 0.0
  pitch: 0.0
  yaw: -0.7
