sensor_kit_base_link2velodyne_top_base_link:
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
sensor_kit_base_link2livox_front_left_base_link:
  x: 1.054
  y: 0.260
  z: -1.330
  roll: 0.0
  pitch: 0.0
  yaw: 1.0471975511965976
sensor_kit_base_link2livox_front_center_base_link:
  x:  1.054
  y: 0.0
  z: -1.330
  roll: 0.00
  pitch: 0.00
  yaw: 0.0
sensor_kit_base_link2livox_front_right_base_link:
  x: 1.054
  y: -0.260
  z: -1.330
  roll: 0.0
  pitch: 0.0
  yaw: -1.0471975511965976
